### ISSUE TITLE
[bug] aio-orc-api deployment does not use hosts proxy settings

### ISSUE THREAD

**Issue by derbl4ck** [Azure/azure-iot-operations#31]
**Describe the bug**
While deploying Azure IoT Operations on a clean installed AKS EE Instance within a corporate environment using a Proxy, the container `symphony-api` is not using the hosts (AKS EE Node) proxy settings. As a result the `symphony-api` container is not able to pull a helm chart, which is the reason why the deploy CLI-Command fails.

**Steps to reproduce**
Run the `az iot ops init` CLI-command targeting a AKS EE Instance which is using a corporate proxy. 

Example aksedge-config.json:
```json
{
  "SchemaVersion": "1.9",
  "Version": "1.0",
  "DeploymentType": "SingleMachineCluster",
  "Network": {
    "NetworkPlugin": "calico",
    "Ip4AddressPrefix": "192.168.1.0/24",
    "InternetDisabled": false,
    "SkipDnsCheck": false,
    "Proxy": {
      "Http": "http://xxxxxx.sme.zscaler.net:80",
      "Https": "http://xxxxxx.sme.zscaler.net:80",
      "No": "localhost,127.0.0.0/8,192.168.0.0/16,172.17.0.0/16,10.42.0.0/16,10.43.0.0/16,10.96.0.0/12,10.244.0.0/16,.svc"
    }
  }
...
}

```

**Hot fix**
To fix the Issue I added the environment variables `NO_PROXY`, `HTTP_PROXY` and `HTTPS_PROXY` to the `symphony-api` container and mounted the hostPath `/etc/pki/ca-trust/source/anchors/` as volume to `symphony-api` container under `/etc/pki/tls/certs/`.

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: aio-orc-api
  namespace: azure-iot-operations
spec:
  template:
    spec:
      volumes:
	  …
        - name: hosts-trusted-certs
          hostPath:
            path: /etc/pki/ca-trust/source/anchors/
            type: Directory
      containers:
        - name: symphony-api
          image: mcr.microsoft.com/azureiotoperations/aio-orc-api:official-20231129.1
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          ...
          env:
            …
            - name: HTTP_PROXY
              value: http://xxxxxx.sme.zscaler.net:80
            - name: HTTPS_PROXY
              value: http://xxxxxx.sme.zscaler.net:80
            - name: NO_PROXY
              value: >-
                localhost,127.0.0.0/8,192.168.0.0/16,172.17.0.0/16,10.42.0.0/16,10.43.0.0/16,10.96.0.0/12,10.244.0.0/16,.svc
          resources: {}
          volumeMounts:
            ...
            - name: hosts-trusted-certs
              readOnly: true
              mountPath: /etc/pki/tls/certs/
```

**Next steps**
We should make sure that our helm chart is using the nodes proxy configuration and the `symphony-api` container trusts the proxy certificate as we cannot rely on the AKS EE proxy functionality as proved due to this bug.

**Cluster Environment**
- AKS EE Arc Agent version: 1.14.5
- AKS EE Kubernetes version: 1.26.6

**Developer Environment**
- CLI Client-OS: Windows 10 Enterprise
- Shell: powershell
- Az CLI version: 2.54.0
- IoT extension version: 0.2.0b1
